#pragma once
#include <cerrno>

#define INK_START_ERRNO 20000

#define SOCK_ERRNO INK_START_ERRNO
#define NET_ERRNO INK_START_ERRNO + 100
#define CACHE_ERRNO INK_START_ERRNO + 400
#define HTTP_ERRNO INK_START_ERRNO + 600

#define ENET_THROTTLING (NET_ERRNO + 1)
#define ENET_CONNECT_TIMEOUT (NET_ERRNO + 2)
#define ENET_CONNECT_FAILED (NET_ERRNO + 3)

#define ESOCK_DENIED (SOCK_ERRNO + 0)
#define ESOCK_TIMEOUT (SOCK_ERRNO + 1)
#define ESOCK_NO_SOCK_SERVER_CONN (SOCK_ERRNO + 2)

#define ECACHE_NO_DOC (CACHE_ERRNO + 0)
#define ECACHE_DOC_BUSY (CACHE_ERRNO + 1)
#define ECACHE_DIR_BAD (CACHE_ERRNO + 2)
#define ECACHE_BAD_META_DATA (CACHE_ERRNO + 3)
#define ECACHE_READ_FAIL (CACHE_ERRNO + 4)
#define ECACHE_WRITE_FAIL (CACHE_ERRNO + 5)
#define ECACHE_MAX_ALT_EXCEEDED (CACHE_ERRNO + 6)
#define ECACHE_NOT_READY (CACHE_ERRNO + 7)
#define ECACHE_ALT_MISS (CACHE_ERRNO + 8)
#define ECACHE_BAD_READ_REQUEST (CACHE_ERRNO + 9)

#define EHTTP_ERROR (HTTP_ERRNO + 0)

const char *InkStrerror(int ink_errno);
