#pragma once

#include "I_SplitDNSProcessor.h"

#define SPLITDNS_MODULE_MAJOR_VERSION 1
#define SPLITDNS_MODULE_MINOR_VERSION 0
#define SPLITDNS_MODULE_VERSION \
  makeModuleVersion(SPLITDNS_MODULE_MAJOR_VERSION, SPLITDNS_MODULE_MINOR_VERSION, PUBLIC_MODULE_HEADER)
